APP_KEY = """-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpMKG97jAoDjQ0YT3
N+/MyxYzdqhRo2ReC4TMy2KlMUugCgYIKoZIzj0DAQehRANCAASYpQ1kSJpht7xk
yg303cOWYgNEGc+WTWYzKFwixmqcfSnDpPjYdshLBX8TY1imt15G7cD8dvfBAsoX
0UPgBfDz
-----END PRIVATE KEY-----"""